### ISSUE TITLE
Application manifest is not semantically valid.

### ISSUE THREAD

**Issue by reximus-bbs** [microsoft/XmlNotepad#105]
Trying to use the ClickOnce Installer and I get an error.
![image](https://user-images.githubusercontent.com/87334962/125339753-9ea46f80-e31f-11eb-99c7-cee73a95c2dc.png)

Tested on three machines all with the same error.

Full error log below.
Wondering if it's the double slash on line 150:

  <file name="runtimes\win-arm64\native**\\**WebView2Loader.dll" size="124328">

![image](https://user-images.githubusercontent.com/87334962/125340279-4752cf00-e320-11eb-8955-124d4a51820e.png)

`PLATFORM VERSION INFO
	Windows 			: 10.0.19042.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4360.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/Fake%20Name/XmlNotepad.application
	Deployment Provider url		: https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad/XmlNotepad.application
						Server		: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

IDENTITIES
	Deployment Identity		: XmlNotepad.application, Version=2.8.0.35, Culture=neutral, PublicKeyToken=ab3ea86545595e2b, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Fake Name\XmlNotepad.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad/Application%20Files/XmlNotepad_2_8_0_35/XmlNotepad.exe.manifest: the manifest may not be valid or the file could not be opened.
		+ Application manifest is not semantically valid.
		+ File element runtimes\win-arm64\native\\WebView2Loader.dll must have a relative path.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2021-07-12 2:36:13 PM] : Activation of C:\Users\Fake Name\XmlNotepad.application has started.
	* [2021-07-12 2:36:13 PM] : Processing of deployment manifest has successfully completed.
	* [2021-07-12 2:36:13 PM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2021-07-12 2:36:13 PM] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad/Application%20Files/XmlNotepad_2_8_0_35/XmlNotepad.exe.manifest: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestSemanticValidation)
		- Application manifest is not semantically valid.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSemanticsForApplicationRole()
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestComponentSemanticValidation)
		- File element runtimes\win-arm64\native\\WebView2Loader.dll must have a relative path.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateFile(File f)
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSemanticsForApplicationRole()

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

`

**Comment by reximus-bbs** [comment]
I have no idea what I'm looking for or if I can make a pull request but maybe it's fixed here:

Line 400 of XmlNotepad/src/Application/Application.csproj

![image](https://user-images.githubusercontent.com/87334962/125348030-b41e9700-e329-11eb-9043-683e49215c11.png)

**Comment by lovettchris** [comment]
Thanks for the bug report, it is fixed now.

**Comment by reximus-bbs** [comment]
Awesome!!  Thank you Chris, just updated successfully!
